"""Tests for the M1 declarative style-pack core."""

import importlib
import json
import shutil
from pathlib import Path

import pytest
import yaml

from dkit.stylepack.errors import (
    StylePackCompatibilityError,
    StylePackFingerprintError,
    StylePackManifestError,
    StylePackResourceError,
)
from dkit.stylepack.fingerprint import fingerprint_root
from dkit.stylepack.loader import StylePackLoader
from dkit.stylepack.model import StylePackReference


FIXTURE_ROOT = Path(__file__).parent / "data" / "stylepack"
STYLE_ROOT = FIXTURE_ROOT / "blue"


class FixtureDistribution:
    """Distribution-like object that exposes the fixture without importing it."""

    version = "0.1.0"

    def locate_file(self, relative_path):
        return FIXTURE_ROOT / relative_path


def reference(fingerprint=None):
    """Build a reference to the test style distribution."""
    return StylePackReference(
        name="dkit-blue",
        distribution="test-style-pack",
        manifest="blue/style.yaml",
        fingerprint=fingerprint,
    )


def copy_fixture(tmp_path):
    """Copy the fixture into a temporary distribution root."""
    root = tmp_path / "stylepack"
    shutil.copytree(FIXTURE_ROOT, root)
    return root, root / "blue"


def test_loader_reads_typed_manifest_without_importing_style_package(monkeypatch):
    """Loading uses distribution paths and never imports a provider package."""
    original = importlib.import_module

    def fail_import(name, package=None):
        if name.startswith("test_style_pack"):
            raise AssertionError("style package must not be imported")
        return original(name, package)

    monkeypatch.setattr(importlib, "import_module", fail_import)
    pack = StylePackLoader().load(reference(), FixtureDistribution())

    assert pack.manifest.id == "dkit-blue"
    assert pack.manifest.page.size == "a4"
    assert pack.manifest.formats.latex.class_name == "dkit-blue"
    assert pack.resource("html/document.css").is_file()


def test_loader_accepts_registered_fingerprint():
    """A fingerprint produced from the style root is accepted."""
    expected = fingerprint_root(STYLE_ROOT)

    pack = StylePackLoader().load(
        reference(expected), FixtureDistribution()
    )

    assert pack.reference.fingerprint == expected


def test_fingerprint_changes_when_a_resource_changes(tmp_path):
    """Any changed file invalidates the style-root fingerprint."""
    _, root = copy_fixture(tmp_path)
    original = fingerprint_root(root)
    (root / "html" / "document.css").write_text(
        "body { color: #000000; }\n", encoding="utf-8"
    )

    assert fingerprint_root(root) != original


def test_fingerprint_ignores_transient_python_bytecode(tmp_path):
    """Pip-generated bytecode does not invalidate a style registration."""
    _, root = copy_fixture(tmp_path)
    original = fingerprint_root(root)
    cache = root / "html" / "__pycache__"
    cache.mkdir()
    (cache / "document.cpython-313.pyc").write_bytes(b"bytecode")

    assert fingerprint_root(root) == original


def test_loader_rejects_a_stale_fingerprint(tmp_path):
    """A registered digest cannot be reused after a resource changes."""
    fixture_root, style_root = copy_fixture(tmp_path)
    expected = fingerprint_root(style_root)
    (style_root / "html" / "document.css").write_text(
        "body { color: #000000; }\n", encoding="utf-8"
    )

    with pytest.raises(StylePackFingerprintError):
        StylePackLoader().load(
            reference(expected), FixtureDistributionAt(fixture_root)
        )


class FixtureDistributionAt(FixtureDistribution):
    """Distribution-like object rooted at a temporary fixture copy."""

    def __init__(self, root):
        self.root = root

    def locate_file(self, relative_path):
        return self.root / relative_path


class EditableFixtureDistribution(FixtureDistributionAt):
    """Fixture distribution whose metadata points to an editable checkout."""

    def __init__(self, root, direct_url):
        super().__init__(root)
        self.direct_url = direct_url

    def read_text(self, filename):
        if filename == "direct_url.json":
            return self.direct_url
        return None


def editable_distribution(tmp_path, source_layout=False):
    """Create an editable distribution with no installed package resources."""
    installed_root = tmp_path / "site-packages"
    installed_root.mkdir()
    project_root = tmp_path / "style-project"
    package_root = project_root / "src" if source_layout else project_root
    package_root.mkdir(parents=True)
    shutil.copytree(FIXTURE_ROOT, package_root, dirs_exist_ok=True)
    direct_url = json.dumps({
        "dir_info": {"editable": True},
        "url": project_root.as_uri(),
    })
    return EditableFixtureDistribution(installed_root, direct_url), package_root


def test_loader_uses_flat_editable_distribution_source(tmp_path):
    """A PEP 660 flat-layout package resolves its source manifest."""
    distribution, package_root = editable_distribution(tmp_path)

    pack = StylePackLoader().load(reference(), distribution)

    assert pack.root == package_root / "blue"


def test_loader_uses_src_editable_distribution_source(tmp_path):
    """A PEP 660 src-layout package resolves its source manifest."""
    distribution, package_root = editable_distribution(tmp_path, source_layout=True)

    pack = StylePackLoader().load(reference(), distribution)

    assert pack.root == package_root / "blue"


@pytest.mark.parametrize("direct_url", [
    "not json",
    json.dumps({
        "dir_info": {"editable": True},
        "url": "file://",
    }),
    json.dumps({
        "dir_info": {"editable": False},
        "url": "file:///tmp/style-project",
    }),
    json.dumps({
        "dir_info": {"editable": True},
        "url": "https://example.test/style-project",
    }),
])
def test_loader_rejects_unavailable_editable_manifest(tmp_path, direct_url):
    """Invalid or non-local editable metadata does not bypass validation."""
    distribution = EditableFixtureDistribution(
        tmp_path / "site-packages",
        direct_url,
    )

    with pytest.raises(StylePackManifestError, match="manifest is unavailable"):
        StylePackLoader().load(reference(), distribution)


def test_loader_prefers_an_installed_manifest_over_editable_metadata(tmp_path):
    """A complete wheel installation remains the authoritative source."""
    installed_root, _ = copy_fixture(tmp_path)
    source_root = tmp_path / "style-project"
    shutil.copytree(FIXTURE_ROOT, source_root)
    direct_url = json.dumps({
        "dir_info": {"editable": True},
        "url": source_root.as_uri(),
    })
    distribution = EditableFixtureDistribution(installed_root, direct_url)

    pack = StylePackLoader().load(reference(), distribution)

    assert pack.root == installed_root / "blue"


def test_loader_rejects_invalid_schema(tmp_path):
    """Unsupported manifest schemas fail before resource use."""
    fixture_root, _ = copy_fixture(tmp_path)
    manifest_path = fixture_root / "blue" / "style.yaml"
    values = yaml.safe_load(manifest_path.read_text(encoding="utf-8"))
    values["schema_version"] = 2
    manifest_path.write_text(yaml.safe_dump(values), encoding="utf-8")

    with pytest.raises(StylePackManifestError):
        StylePackLoader().load(reference(), FixtureDistributionAt(fixture_root))


def test_loader_rejects_incompatible_dkit_version(tmp_path):
    """A manifest requiring a newer dkit fails closed."""
    fixture_root, _ = copy_fixture(tmp_path)
    manifest_path = fixture_root / "blue" / "style.yaml"
    values = yaml.safe_load(manifest_path.read_text(encoding="utf-8"))
    values["requires_dkit"] = ">=999.0"
    manifest_path.write_text(yaml.safe_dump(values), encoding="utf-8")

    with pytest.raises(StylePackCompatibilityError):
        StylePackLoader().load(reference(), FixtureDistributionAt(fixture_root))


def test_loader_rejects_resource_traversal(tmp_path):
    """Manifest resources cannot escape the style root."""
    fixture_root, _ = copy_fixture(tmp_path)
    manifest_path = fixture_root / "blue" / "style.yaml"
    values = yaml.safe_load(manifest_path.read_text(encoding="utf-8"))
    values["formats"]["html"]["stylesheet"] = "../outside.css"
    manifest_path.write_text(yaml.safe_dump(values), encoding="utf-8")

    with pytest.raises(StylePackResourceError):
        StylePackLoader().load(reference(), FixtureDistributionAt(fixture_root))


def test_loader_rejects_missing_distribution():
    """A missing installed distribution has an actionable style error."""

    def missing(_name):
        raise ValueError("not installed")

    with pytest.raises(StylePackResourceError, match="not installed"):
        StylePackLoader(missing).load(reference())
