[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "json-keys"
description = "extract json structure"
dynamic = ["version"]

[tool.setuptools.dynamic]
version = {attr = "json_keys.__version__"}

[project.scripts]
json_keys = "json_keys:main"
