#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# dkit documentation build configuration file.
#
# This file is execfile()d with the current directory set to its
# containing dir.

import sys
import os

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
sys.path.insert(0, os.path.abspath('../..'))
sys.path.insert(0, os.path.abspath('.'))

# -- General configuration ------------------------------------------------

extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.coverage',
    'sphinx.ext.viewcode',
    'sphinx.ext.napoleon',
    'sphinx.ext.intersphinx',
    'sphinx.ext.graphviz',
    'sphinx.ext.inheritance_diagram',
    'sphinx.ext.todo',
    'sphinxarg.ext',
]

intersphinx_mapping = {
    'python': ('https://docs.python.org/3', None),
}

# Render graphviz diagrams (including inheritance diagrams) as SVG rather
# than the PNG default, so they stay crisp at any zoom level instead of
# pixelating on complex, larger diagrams.
graphviz_output_format = 'svg'

# Styling for inheritance diagrams: rounded, softly-filled nodes, hollow
# "empty" arrowheads for the conventional UML is-a notation, and extra
# node/rank spacing so denser hierarchies stay readable.
inheritance_graph_attrs = {
    'rankdir': 'LR',
    'nodesep': 0.35,
    'ranksep': 0.6,
    'bgcolor': 'transparent',
}
inheritance_node_attrs = {
    'shape': 'box',
    'style': '"rounded,filled"',
    'fillcolor': '"#eef2fa"',
    'color': '"#4c72b0"',
    'fontcolor': '"#1a1a1a"',
    'fontsize': 11,
    'fontname': '"Helvetica,Arial,sans-serif"',
    'height': 0.3,
}
inheritance_edge_attrs = {
    'arrowhead': 'empty',
    'color': '"#4c72b0"',
    'penwidth': 0.8,
}

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = 'dkit'
copyright = '2026, Cobus Nel'
author = 'Cobus Nel'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
import dkit
version = dkit.__version__
release = dkit.__version__

# The language for content autogenerated by Sphinx.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False


# -- Options for HTML output ----------------------------------------------

html_theme = 'furo'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Output file base name for HTML help builder.
htmlhelp_basename = 'dkitdoc'
